### ISSUE TITLE
Release of The Training Code

### ISSUE THREAD

**Issue by AziziShekoofeh** [shleecs/Copy-and-Paste-Networks-for-Deep-Video-Inpainting#3]
Hi, Thanks for the great package, I am just wondering if you have any plan to release the training code or giving more details about how we could train the network. Thanks.

**Comment by AziziShekoofeh** [comment]
Also, you have mentioned in many places in the paper that "The details on the architecture will
be described in the supplementary materials". By the supplementary material you meant the code or there is any supplementary material or appendix section that I cannot find. Thanks. :)

**Comment by shleecs** [comment]
Hello,
Thank you for your interest about our works.
We are so sorry that couldn't release our training code because of the policy with industrial collaboration.
And you can download the supplementary material as download links.
https://www.dropbox.​com/s/mteo5artx5jb4n​h/2855-supp.pdf?dl=1 
If you have question for our works during implementation, please e-mail to us.
Thank you!

**Comment by shleecs** [comment]
Hello,
 Thank you for your interest about our works.
 We are so sorry that couldn't release our training code because of the policy with industrial collaboration.
 And you can download our supplementary material from the link below.
https://www.dropbox.​com/s/mteo5artx5jb4n​h/2855-supp.pdf?dl=1
 If you have question for our works during implementation, please e-mail to us.
 Thank you!

**Comment by AziziShekoofeh** [comment]
@shleecs Thanks for the explanation, however, the above link is not working and is not available. I think it has some access restriction setup. Thanks.

**Comment by shleecs** [comment]
I'm so sorry that our link doesn't work.
Can you access below link?
https://www.dropbox.com/s/mteo5artx5jb4nh/2855-supp.pdf?dl=0
Thanks.

**Comment by AziziShekoofeh** [comment]
@shleecs Great. Thanks for sharing, it is working now. :)
