### ISSUE TITLE
How to back-propagate to the alignment encoder and regressor?

### ISSUE THREAD

**Issue by y60** [shleecs/Copy-and-Paste-Networks-for-Deep-Video-Inpainting#4]
Thank you for releasing the codes of your great work!
I am interested in how to back-propagate to the alignment encoder and regressor .
Could you please give me details?

**Comment by shleecs** [comment]
Hello! Thank you for your interest for our works.

The alignment encoder and regressor are trained with self-supervised method.

Our alignment network extracts the affine matrix for aligning reference frame toward the target frame. 

Our model computes the L_align loss between target frame and aligned reference frames(warped by affine matrix). 

Furthermore, the other loss also affects the training the alignment networks, because our model is end-to-end deep neural networks, 

You can find the details in our papers. Thank you!

**Comment by y60** [comment]
Thank you very much for your detailed answer and it completely solved my question.  (I did't know `functional. grid_sample` propagates the grad to the input grid. I am sorry for my misunderstanding.)
